services:
  telegram-bot:
    build: .
    platform: linux/amd64
    container_name: telegram-transcription-bot
    env_file:
      - .env
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped
    
    # Remove healthcheck since we don't have a health endpoint
    # The bot will log its status instead 