version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-transcription-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-50}
      - TEMP_DIR=/app/temp
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEEPGRAM_MODEL=${DEEPGRAM_MODEL:-nova-2}
      - DEEPGRAM_LANGUAGE=${DEEPGRAM_LANGUAGE:-en}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-sonnet-20240229}
      - CLAUDE_MAX_TOKENS=${CLAUDE_MAX_TOKENS:-4000}
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 